<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <title>Batitom</title>
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
        <script src="https://kit.fontawesome.com/b4de938588.js" crossorigin="anonymous"></script>
        <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
        <link rel="stylesheet" href="<?= Router::getInstance()->getWwwPath() ?>/css/style.css">
    </head>
    <body>
        <header>
                <div>
                    <a href="<?=Router::getInstance()->generateUrl("batitom_devis_calculate") ?>">  <img src="<?= Router::getInstance()->getWwwPath() ?>/img/logo.jpg" alt="logo"> </a>
                </div>
                <div class="connection">
                    <div class="admin-panel">
                        <?php if(UserSession::getInstance()->isAuthenticated()): ?>
                            <p>Bonjour <?= UserSession::getInstance()->getForname() ?>!</p>
                            <a href="<?=Router::getInstance()->generateUrl("batitom_user_logout") ?>">  <i class="far fa-user">  </i> se déconnecter  </a>
                        <?php else: ?>
                            <a href="<?=Router::getInstance()->generateUrl("batitom_user_login") ?>">  <i class="far fa-user">  </i> se connecter  </a>
                            <a href="<?=Router::getInstance()->generateUrl("batitom_user_create") ?>">  <i class="fas fa-sign-in-alt">  </i> Créer votre compte  </a>
                        <?php endif; ?>
                        <?php if(UserSession::getInstance()->isAdmin()): ?>
                            <a href="<?= Router::getInstance()->generateUrl("batitom_pricelist_create")?>">Ajouter un élement de liste de prix</a>
                            <a href="<?= Router::getInstance()->generateUrl("batitom_formquestion_create")?>">Ajouter une option de calculatrice</a> 
                            <a href="<?= Router::getInstance()->generateUrl("batitom_pricelist_showall")?>">Editer une liste de prix</a>   
                        <?php endif; ?>         
                    </div> 
                </div>
        </header>
        <main>
            <aside>
                <?php foreach (Flashbag::getInstance()->consumeAllMessages() as $message): ?>
                    <div class ="flash-message">
                        <?= $message ?>
                    </div>
                <?php endforeach; ?>
            </aside>
            <?php include $templatePath ?>
        </main>
        <?php if (isset($neededScripts)): ?>
        <?php foreach($neededScripts as $script) :?>
            <script src="<?= Router::getInstance()->getWwwPath()?>/js/<?= $script?>"></script>
        <?php endforeach;?>
    <?php endif; ?>
    </body>
</html>
