<h1> Votre estimation est prête ! </h1>
<p> La création de votre compte est nécessaire pour consulter votre estimation. Vous pourrez également y suivre l'évolution du prix des biens estimés. </p>
<form>
    <input type="text" name="forname" placeholder="prenom" data-required >
    <input type="text" name="name" placeholder="nom" data-required >
    <input type="text" name="email" placeholder="email"  data-email >
    <input type="text" name="numTel" placeholder="numero de telephone" data-required   >
    <input type="submit" value="Ajouter">
</form>